---
env:
  global:
    - BACKEND_TEST_CONFIG_FILE=tests_configs.ini
    - DEFAULT_SQLITE_SQLALCHEMY__URL=sqlite:////tmp/tracim.sqlite
    - DEFAULT_MYSQL_SQLALCHEMY__URL=mysql+pymysql://root@localhost/tracim_test
    - DEFAULT_POSTGRES_SQLALCHEMY__URL=postgresql://postgres:dummy@127.0.0.1:5432/tracim_test?client_encoding=utf8
    - DB=sqlite
    - TRACIM_SQLALCHEMY__URL=$DEFAULT_SQLITE_SQLALCHEMY__URL
    - TRACIM_SEARCH__ELASTICSEARCH__INDEX_ALIAS=tracim_content_travis_test
    - TRACIM_DEPOT_STORAGE_NAME=test
    - TRACIM_DEPOT_STORAGE_DIR=/tmp/test/depot
    - TRACIM_PREVIEW_CACHE_DIR=/tmp/test/preview_cache
    - TRACIM_COLOR__CONFIG_FILE_PATH=$TRAVIS_BUILD_DIR/backend/color-test.json
sudo: false
language: python
dist: trusty
python:
  - "3.6"

_install_backend: &_install_backend
  addons:
    postgresql: "9.3"
    apt:
      packages:
        - libreoffice
        - imagemagick
        - libmagickwand-dev
        - ghostscript
        - libfile-mimeinfo-perl
        - poppler-utils
        - qpdf
        - libldap2-dev
        - libsasl2-dev
        - docker-ce
        - libimage-exiftool-perl
  services:
    - redis-server
    - mysql
  before_install:
    - docker pull mailhog/mailhog
    - docker run -d -p 1025:1025 -p 8025:8025 mailhog/mailhog
    - docker pull rroemhild/test-openldap
    - docker run -d -p 3890:389 rroemhild/test-openldap
    - docker pull elasticsearch:7.0.0
    - docker run -d -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" -e "cluster.routing.allocation.disk.threshold_enabled=false" elasticsearch:7.0.0
  install:
    - cd $TRAVIS_BUILD_DIR/backend
    - pip install --upgrade pip setuptools
    # using old version of pytest-cov to avoid
    # version conflict with python-coveralls
    # see https://github.com/z4r/python-coveralls/issues/66
    - pip install 'pytest-cov<2.6'
    - pip install python-coveralls
    - pip install -r "requirements.txt"
    # postgresql
    - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database tracim_test;' -U postgres; fi"
    - sh -c "if [ '$DB' = 'postgres' ]; then pip install -e \".[postgresql,testing]\"; fi"
    # mysql
    - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE tracim_test;'; fi"
    - sh -c "if [ '$DB' = 'mysql' ]; then pip install -e \".[mysql,testing]\"; fi"
    # sqlite
    - sh -c "if [ '$DB' = 'sqlite' ]; then pip install -e \".[testing]\"; fi"
    - cd $TRAVIS_BUILD_DIR
  before_script:
    # INFO - G.M - 2019-05-02 - some useful debug information
    - echo "$TRACIM_COLOR__CONFIG_FILE_PATH"
    - cat "$TRACIM_COLOR__CONFIG_FILE_PATH"
    - echo "$TRACIM_SQLALCHEMY__URL"
  after_success:
    - coveralls

_install_full_tracim: &_install_full_tracim
  <<: *_install_backend
  install:
    - cd $TRAVIS_BUILD_DIR/backend
    - pip install --upgrade pip setuptools
    # using old version of pytest-cov to avoid
    # version conflict with python-coveralls
    # see https://github.com/z4r/python-coveralls/issues/66
    - pip install 'pytest-cov<2.6'
    - pip install python-coveralls
    - pip install -r "requirements.txt"
    # postgresql
    - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database tracim_test;' -U postgres; fi"
    - sh -c "if [ '$DB' = 'postgres' ]; then pip install -e \".[postgresql,testing]\"; fi"
    # mysql
    - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE tracim_test;'; fi"
    - sh -c "if [ '$DB' = 'mysql' ]; then pip install -e \".[mysql,testing]\"; fi"
    # sqlite
    - sh -c "if [ '$DB' = 'sqlite' ]; then pip install -e \".[testing]\"; fi"
    # setup backend for running
    - cp ../color.json.sample ../color.json
    - tracimcli db init -c $BACKEND_TEST_CONFIG_FILE
    - alembic -c $BACKEND_TEST_CONFIG_FILE stamp head
    # install frontend
    - cd $TRAVIS_BUILD_DIR
    - ./install_frontend_dependencies.sh root
    - ./build_full_frontend.sh root
    - ./setup_functionnal_tests.sh root

_backend_quick_test: &_backend_quick_test
  <<: *_install_backend
  # INFO - G.M - 2019-04-25 - override docker usage by overriding
  addons:
    apt:
      packages:
        - libimage-exiftool-perl
  services:
  before_install:
  script:
    - cd $TRAVIS_BUILD_DIR/backend/
    - pytest tracim_backend --ignore "tracim_backend/tests/functional" --ignore "tracim_backend/tests/commands"
    - cd $TRAVIS_BUILD_DIR

_backend_test: &_backend_test
  <<: *_install_backend
  script:
    - cd $TRAVIS_BUILD_DIR/backend/
    - pytest --cov tracim_backend
    - cd $TRAVIS_BUILD_DIR


jobs:
  include:
    # TODO BS 2018-10-12: Re-enable this test when setup.py list deps as strict
    #  - stage: quick-tests
    #    name: Check requirement.txt
    #    python:
    #    - "3.5"
    #    addons:
    #    services:
    #    before_install:
    #      - cd backend
    #    install:
    #      - pip install --upgrade pip setuptools
    #      - pip install pip-tools
    #    before_script:
    #      - mv requirements.txt requirements_from_source.txt
    #    script:
    #      - pip-compile
    #      - diff -u requirements.txt requirements_from_source.txt
    #    after_success: true

    # INFO - G.M - 2019-04-25 - Stage: Static tests ###
    - stage: static-tests
      name: fmt
      install:
        - pip install black isort
      script:
        - black --version
        - echo -n "isort " & isort --version-number
        - black -l 100 --exclude '/(\..*)/' --diff --check $TRAVIS_BUILD_DIR/backend/tracim_backend
        - isort -df -c $TRAVIS_BUILD_DIR/backend/tracim_backend/**/*.py
    - stage: static-tests
      name: flake8
      install:
        - pip install flake8
      script:
        - flake8 --version
        - flake8 $TRAVIS_BUILD_DIR/backend/tracim_backend

    # INFO - G.M - 2019-04-25 - Stage: Quick Tests ###
    - stage: quick-tests
      name: "Python: 3.6"
      <<: *_backend_quick_test
      python:
        - "3.6"
    - stage: quick-tests
      name: "Python: 3.5"
      <<: *_backend_quick_test
      python:
        - "3.5"
    - stage: quick-tests
      name: "Python: 3.7"
      dist: xenial
      <<: *_backend_quick_test
      python:
        - "3.7"

    # INFO - G.M - 2019-04-25 - Stage: Backend ###
    - stage: backend
      <<: *_backend_test
      env:
        - DB=postgres
        - TRACIM_SQLALCHEMY__URL=$DEFAULT_SQLITE_SQLALCHEMY__URL
    - stage: backend
      <<: *_backend_test
      env:
        - DB=postgres
        - TRACIM_SQLALCHEMY__URL=$DEFAULT_POSTGRES_SQLALCHEMY__URL
    - stage: backend
      <<: *_backend_test
      env:
        - DB=mysql
        - TRACIM_SQLALCHEMY__URL=$DEFAULT_MYSQL_SQLALCHEMY__URL
    # INFO - G.M - 2019-04-25 - Stage: Functional Test ###
    - stage: functional
      name: Functional tests using Cypress
      <<: *_install_full_tracim
      env:
        - DB=sqlite;
        - TRACIM_SQLALCHEMY__URL=sqlite:////tmp/tracim_cypress.sqlite
        - BACKEND_TEST_CONFIG_FILE=cypress_test.ini
        - TRAVIS_NODE_VERSION="10"
      script:
        - cd $TRAVIS_BUILD_DIR/backend
        - nohup pserve $BACKEND_TEST_CONFIG_FILE >pserve.log 2>&1 &
        - cd $TRAVIS_BUILD_DIR/functionnal_tests
        - npm run travis-cypress-run
        - cd $TRAVIS_BUILD_DIR
      after_failure:
        - cat $TRAVIS_BUILD_DIR/backend/pserve.log

stages:
  - functional
  - static-tests
  - quick-tests
  - backend
